config/routes.rb
Quotable::Application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :dashboard
  resources :proposals
  resources :product_items
  resources :units
  

  root :to => 'home#index'

  mount Ckeditor::Engine => "/ckeditor"
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name
  
  has_many :users
  has_many :product_items
end

app/models/product_item.rb
class ProductItem < ActiveRecord::Base
  attr_accessible :name, :description
  attr_accessible :company_id, :unit_id
  
  belongs_to :company
  belongs_to :unit
  
  has_many :product_item_prices
end

app/models/product_item_price.rb
class ProductItemPrice < ActiveRecord::Base
  attr_accessible :price_per_unit, :is_current
  attr_accessible :product_item_id
  
  belongs_to :product_item
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  attr_accessible :name
  attr_accessible :user_id
  
  belongs_to :user
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :company_id
  attr_accessible :first_name, :last_name
  
  belongs_to :company
  
  has_many :proposals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  layout "flatly"
  
  after_filter  :set_csrf_cookie_for_ng 
  
protected

  def after_sign_in_path_for(resource)
    dashboard_index_path
  end
  
  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end
  
  def verified_request?
    super || form_authenticity_token == request.headers['X_XSRF_TOKEN']
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @proposals = Proposal.all
    
    respond_to do |format|
      format.html
      format.json { render :json => @proposals }
      format.xml { render :xml => @proposals }
    end
  end

  def show
    @proposal = Proposal.find(params[:id])
  end

  def new
    @proposal = Proposal.new
  end

  def edit
    @proposal = Proposal.find(params[:id])
  end

  def create
    @proposal = Proposal.new(params[:proposal])

    if @proposal.save
      flash[:success] = "Proposal has been created"
      redirect_to :action => :index
    else
      render :action => :new
    end
  end
  
  def update
    @proposal = Proposal.find(params[:id])

    if @proposal.save
      flash[:success] = "Proposal has been updated"
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def destroy
    @proposal = Proposal.find(params[:id])
    @proposal.destroy

    flash[:success] = "Proposal was successfully deleted"
    redirect_to :action => :index
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @units = Unit.all
    
    respond_to do |format|
      format.html
      format.json { render :json => @units }
      format.xml { render :xml => @units }
    end
  end

  def show
    @unit = Unit.find(params[:id])
  end

  def new
    @unit = Unit.new
  end

  def edit
    @unit = Unit.find(params[:id])
  end

  def create
    @unit = Unit.new(params[:unit])

    if @unit.save
      flash[:success] = "Unit has been created"
      redirect_to :action => :index
    else
      render :action => :new
    end
  end
  
  def update
    @unit = Unit.find(params[:id])

    if @unit.save
      flash[:success] = "Unit has been updated"
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    flash[:success] = "Unit was successfully deleted"
    redirect_to :action => :index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @users = User.all
  end
  
  def show
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_item_prices_helper.rb
module ProductItemPricesHelper
end

app/helpers/product_items_helper.rb
module ProductItemsHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Quotable" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
	  
	  <div id="wrapper">
		  <%= render "partials/header" %>
		  
	      <div class="container-fluid">
	        <div class="row-fluid">
	          <div class="span3">
	            <div class="well sidebar-nav">
	              <ul class="nav nav-list">
	                <li class="nav-header">Sidebar</li>
	                <li><%= link_to "Link1", "/path1"  %></li>
	                <li><%= link_to "Link2", "/path2"  %></li>
	                <li><%= link_to "Link3", "/path3"  %></li>
	              </ul>
	            </div><!--/.well -->
	          </div><!--/span-->
	          <div class="span9">
	            <%= bootstrap_flash %>
	            <%= yield %>
	          </div>
	        </div><!--/row-->

	        <footer>
	          <p>&copy; Company 2013</p>
	        </footer>

	      </div> <!-- /container -->
	  </div><!-- /#wrapper -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/cyborg.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "quotable" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "cyborg", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
	<div id="wrapper">
	  <%= render "partials/header" %>
	  <%= bootstrap_flash %>
	  <%= yield %>
	  <footer>
	    <p>&copy; Company 2013</p>
	  </footer>
	</div><!-- /#wrapper -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "cyborg" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>

app/views/layouts/flatly.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Quotable" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "flatly", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>
	  <div id="wrapper">
		  <%= render "partials/header" %>
		  <div class="container">
		    <%= bootstrap_flash %>
		    <%= yield %>
	      </div>
		  <%= render "partials/footer" %>
	  </div><!-- /#wrapper -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "flatly" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>

app/views/partials/_footer.html.erb
<div class="container">
  <footer>
    <p>&copy; Axon IT Consulting 2013</p>
  </footer>
</div>

app/views/partials/_header.html.erb
<div class="navbar navbar-fixed-top ">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Quotable", root_path, :class => "brand" %>
      <div class="container-fluid nav-collapse pull-right">
        <ul class="nav">
			<% if user_signed_in? %>
			  <li><%= link_to current_user.first_name + " " + current_user.last_name, edit_user_registration_path %></li>
			  <li><%= link_to( "Logout" , destroy_user_session_path, method: :delete ) %></li>
			<% else %>
              <li><%= link_to "Sign In" , new_user_session_path %></li>
              <li><%= link_to "Sign Up" , new_user_registration_path %></li>
			<% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar-inner -->
</div><!-- /.navbar navbar-fixed-top-->

<% if user_signed_in? %>
  <div id="subnav" class="navbar navbar-inverse container">
	  <div class="navbar-inner">
		  <div class="container">
			  <%= link_to current_user.company.name, root_path, :class => "brand" %>
			  <div>
				  <ul class="nav">
					  <li><%= link_to "Dashboard", dashboard_index_path %></li>
					  <li><%= link_to "Proposals", proposals_path %></li>
					  <li><%= link_to "Product Items", product_items_path %></li>
				  </ul><!-- /.nav -->
			  </div>
		  </div><!-- /.container -->
	  </div><!-- /.navbar-inner -->
  </div><!-- /.navbar navbar-inverse -->
<% end %>